name: Nightly releases

# on:
#   schedule:
#     cron: "0 0 * * *" # Executes every day at 12 midnight UTC
on: watch # TODO: Remove this once workflow has been tested

jobs:
  deploy:
    #runs-on: macOS-latest # TODO: Move back to Ubuntu once Android 29 support has been added
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Android SDK Platform 29 and Build-Tools 29.0.2
      run: |
        cd
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        rm sdk-tools-linux-4333796.zip
        mkdir android-sdk
        mv tools android-sdk/tools

        echo "Available Platform Tools:"
        ls -hAFl --color=auto ~/android-sdk/tools/bin
        echo "Adding Android SDK to PATH..."
        echo "# Export the Android SDK path" >> ~/.profile
        echo "export ANDROID_HOME=$HOME/android-sdk" >> ~/.profile
        echo "export PATH=$PATH:$ANDROID_HOME/tools/bin" >> ~/.profile
        echo -e "export PATH=$PATH:$ANDROID_HOME/platform-tools" >> ~/.profile
        echo -e "\n# Fixes sdkmanager error with java versions higher than java 8" >> ~/.profile
        echo "export JAVA_OPTS='-XX:+IgnoreUnrecognizedVMOptions --add-modules java.se.ee'" >> ~/.profile
        echo "Result of cat ~/.profile:"
        cat ~/.profile
        source ~/.profile
        echo "Installing Android SDK Platform 29 and Build-Tools 29.0.2 with sdkmanager..."
        sudo sdkmanager "build-tools;29.0.2" "platforms;android-29"
    - name: Install GPG2
      run: sudo apt-get install gnupg2
    - name: Install Homebrew
      run: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
        sudo apt-get install build-essential curl file git
        echo "Current path:"
        echo $PATH
    - name: Install Homebrew dependencies
      run: |
        source ~/.profile
        brew bundle
    - name: Decrypt keystore
      run: |
        source ~/.profile
        transcrypt -c ${{ secrets.TRANSCRYPT_CIPHER }} -p ${{ secrets.TRANSCRYPT_PASSWORD }}
      env:
        SECRETS_GPG_COMMAND: gpg2
    - name: Build app
      run: ./gradlew :app:assembleNightly # APK is available at app/build/outputs/apk/nightly/app-nightly.apk
      env:
        CI: ${{ true }}
    - name: Create nightly tag
      run: |
        recent_tag=$(git describe --tags $(git ls-remote --tags -q | awk '{print $2}' | sed -e "s/refs\/tags\///" \
        | grep -o 'v[0-9.]*[^-NIGHTLY]' | sort -u | tail -1))
        tag_name="$recent_tag-NIGHTLY-$(date +'%Y-%m-%d-%H%M%S')"
        if git rev-parse "$tag_name" >/dev/null 2>&1
        then
          echo "##[debug]Skipping creation of nightly tag as nightly tag already exists."
        else
          git tag $tag_name
          echo "Pushing tag to origin..."
          git push origin $tag_name
        fi
    - name: Release
      uses: docker://softprops/action-gh-release
      with:
        files: app/build/outputs/apk/nightly/app-nightly.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
