name: Nightly releases

# on:
#   schedule:
#     cron: "0 0 * * *" # Executes every day at 12 midnight UTC
on: watch # TODO: Remove this once workflow has been tested

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Homebrew dependencies
      uses: artemnovichkov/action-homebrew@0.1.0
      with:
        args: bundle
    - name: Decrypt keystore
      run: git secret reveal -p ${{ secrets.GIT_SECRET_PASSPHRASE }}
    - name: Build app
      run: ./gradlew :app:assembleNightly # APK is available at app/build/outputs/apk/nightly/app-nightly.apk
    - name: Create nightly tag
      run: |
        recent_tag=$(git describe --tags $(git ls-remote --tags -q | awk '{print $2}' | sed -e "s/refs\/tags\///" \
        | grep -o 'v[0-9.]*[^-NIGHTLY]' | sort -u | tail -1))
        tag_name="$recent_tag-NIGHTLY-$(date +'%Y-%m-%d-%H%M%S')"
        if git rev-parse "$tag_name" >/dev/null 2>&1
        then
          echo "##[debug]Skipping creation of nightly tag as nightly tag already exists."
        else
          git tag $tag_name
          echo "Pushing tag to origin..."
          git push origin $tag_name
        fi
    - name: Release
      uses: docker://softprops/action-gh-release
      with:
        files: app/build/outputs/apk/nightly/app-nightly.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
